[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["dependencies"]
name = "src"
version = "0.1.0"
description = "pyb2023 - graph data science"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.in"]}
